version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: hellodb
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Tokyo"
    restart: always
