let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.14.4-20211109/packages.dhall sha256:e8d8d5b339f6d46d950da90037c6c38e8809f7e34f727373089ab82c080fc709

in  upstream
  with
    postgresql-client =
      { dependencies =
        [ "aff"
        , "argonaut"
        , "arrays"
        , "assert"
        , "bifunctors"
        , "bytestrings"
        , "datetime"
        , "decimals"
        , "dotenv"
        , "effect"
        , "either"
        , "enums"
        , "exceptions"
        , "foldable-traversable"
        , "foreign"
        , "foreign-generic"
        , "foreign-object"
        , "identity"
        , "integers"
        , "js-date"
        , "lists"
        , "math"
        , "maybe"
        , "newtype"
        , "node-process"
        , "nullable"
        , "ordered-collections"
        , "partial"
        , "polyform"
        , "polyform-batteries-core"
        , "polyform-batteries-env"
        , "prelude"
        , "psci-support"
        , "string-parsers"
        , "strings"
        , "test-unit"
        , "transformers"
        , "tuples"
        , "typelevel-prelude"
        , "validation"
        ]
      , repo = "https://github.com/rightfold/purescript-postgresql-client"
      , version = "v3.3.0"
      }
  with
    polyform = 
      { dependencies =
        [ "arrays"
        , "bifunctors"
        , "control"
        , "effect"
        , "either"
        , "enums"
        , "functors"
        , "heterogeneous"
        , "identity"
        , "invariant"
        , "lists"
        , "maybe"
        , "newtype"
        , "ordered-collections"
        , "parallel"
        , "partial"
        , "prelude"
        , "profunctor"
        , "psci-support"
        , "quickcheck"
        , "quickcheck-laws"
        , "record"
        , "transformers"
        , "tuples"
        , "type-equality"
        , "typelevel-prelude"
        , "unsafe-coerce"
        , "validation"
        , "variant"
        ]
      , repo = "https://github.com/purescript-polyform/polyform"
      , version = "v0.9.0"
      }
  with
    polyform-batteries-core = 
      { dependencies =
        [ "arrays"
        , "decimals"
        , "effect"
        , "enums"
        , "integers"
        , "lazy"
        , "maybe"
        , "numbers"
        , "partial"
        , "polyform"
        , "prelude"
        , "psci-support"
        , "quickcheck"
        , "strings"
        , "test-unit"
        , "typelevel-prelude"
        , "unsafe-coerce"
        , "validation"
        , "variant"
        ]
      , repo = "https://github.com/purescript-polyform/batteries-core"
      , version = "v0.2.0"
      }
  with
    polyform-batteries-env =
      { dependencies =
          [ "arrays"
          , "identity"
          , "maybe"
          , "ordered-collections"
          , "polyform"
          , "polyform-batteries-core"
          , "prelude"
          , "psci-support"
          , "typelevel-prelude"
          ]
      , repo = "https://github.com/purescript-polyform/batteries-env"
      , version = "v0.1.0"
      }
  with
    selda = 
      { dependencies =
          [ "aff"
          , "arrays"
          , "bifunctors"
          , "console"
          , "datetime"
          , "dodo-printer"
          , "dotenv"
          , "effect"
          , "either"
          , "enums"
          , "exceptions"
          , "exists"
          , "foldable-traversable"
          , "foreign"
          , "foreign-object"
          , "heterogeneous"
          , "leibniz"
          , "lists"
          , "maybe"
          , "newtype"
          , "node-process"
          , "node-sqlite3"
          , "ordered-collections"
          , "partial"
          , "polyform"
          , "polyform-batteries-core"
          , "polyform-batteries-env"
          , "postgresql-client"
          , "prelude"
          , "record"
          , "simple-json"
          , "strings"
          , "test-unit"
          , "transformers"
          , "tuples"
          , "typelevel-prelude"
          , "unsafe-coerce"
          , "validation"
          , "variant"
          ]
      , repo = "https://github.com/Kamirus/purescript-selda"
      , version = "master"
      }